# Generated by Django 4.1.5 on 2023-02-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_author_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcontentimage',
            old_name='is_white',
            new_name='is_wide',
        ),
    ]
