# Generated by Django 4.1.5 on 2023-02-02 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_is_white_subcontentimage_is_wide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AlterField(
            model_name='subcontentimage',
            name='sub_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subimage', to='blog.subcontent'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
            preserve_default=False,
        ),
    ]
