# Generated by Django 4.1.4 on 2023-03-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_article_views_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='view',
            field=models.IntegerField(default=1),
        ),
    ]
