# Generated by Django 4.1.4 on 2023-04-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
