# Generated by Django 4.1.4 on 2023-04-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
