# Generated by Django 4.1.5 on 2023-02-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleAbout',
        ),
    ]
